# Name of workflow
name: Cypress Tests

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - feature
      - develop

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    #steps in job
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        # Install npm dependencies, cache them correctly
        # and run all Cypress tests
        - name: Cypress run
          uses: cypress-io/github-action@v6
          with:
            component: true